### ISSUE TITLE
Player list not working with more than 1 Admin

### ISSUE THREAD

**Issue by D3RFLO** [SchnitzelPommes/DayZ-SA-Tomato#12]
Describe the bug
When there are atleast 2 Admins on the Server the player list is just working for one. For the other one the list is empty

To Reproduce

Expected behavior
show player in menu

**Comment by SchnitzelPommes** [comment]
okay fixable should be in the next update

**Comment by SchnitzelPommes** [comment]
Does the map work for both admins?

**Comment by D3RFLO** [comment]
Nope the map is also just working for 1 admin

**Comment by SchnitzelPommes** [comment]
fixed
