### ISSUE TITLE
It can't support dayz 1.0 now

### ISSUE THREAD

**Issue by AndyLee1024** [SchnitzelPommes/DayZ-SA-Tomato#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SchnitzelPommes** [comment]
Just fixed

**Comment by AndyLee1024** [comment]
It's works fine. thank you mate.
