### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by krcenov** [SchnitzelPommes/DayZ-SA-Tomato#2]
**Describe the bug**
The server crashes on startup without a reason.

**To Reproduce**

verifySignatures = 0;  

1. Start server with mod
2. Let a player join server
3. See error

**Expected behavior**
Not to crash.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Latest

Before crash
14:04:05 Players: 0 in total
14:04:05 [LoginMachine]: Add player Survivor (152571661)
14:04:05 [StateMachine]: Player Survivor (dpnid 152571661 uid ) Entering PreCreatePlayerLoginState
14:04:05 BattlEye Server: Player #0 Survivor (192.168.1.1:2304) connected
14:04:05 BattlEye Server: Player #0 Survivor - BE GUID: a2578f2b9d5effe2d7afe393e383d30a
14:04:05 Player Survivor connecting.
14:04:05 [StateMachine]: Player Survivor (dpnid 152571661 uid ) Entering WaitPreCreatePlayerLoginState
14:04:06 Player Survivor connected (id=eL8T6yOFS6n9cYsr6T2LtFKB3ZNbBC3DrmXassu4rYQ=).
14:04:06 Average server FPS: 16516.00 (measured interval: 1 s)
14:04:06 Used memory: 348725 KB
14:04:06 Players: 1 in total
14:04:07 [StateMachine]: Player Survivor (dpnid 152571661 uid eL8T6yOFS6n9cYsr6T2LtFKB3ZNbBC3DrmXassu4rYQ=) Entering GetCharacterLoginState

**Comment by SchnitzelPommes** [comment]
Gonna look Ingo that when i am back from work

**Comment by Peinful** [comment]
Any chance you can put the full crash log into a pastebin?

**Comment by krcenov** [comment]
@Peinful Where to find DayZ Server crash log?
This is my client log
Log C:\Users\krcen\AppData\Local\DayZ\script.log started at 27.11. 16:37:15
https://pastebin.com/VKuPXjZy

**Comment by SchnitzelPommes** [comment]
Sinc you Opened a second issue with players getting kicked it does not crash anymore?

**Comment by krcenov** [comment]
They still get kicked if verifySignatures = 1;
But if verifySignatures = 0; the server just crashes on player connect.

**Comment by krcenov** [comment]
They still get kicked if verifySignatures = 1;
But if verifySignatures = 0; the server just crashes on player connect.

**Comment by krcenov** [comment]
Problem fixed.
Reason: DayZ-Sa-Tomato is incompatible with (Don't remember the mission mod name)
