### ISSUE TITLE
Update instructions!!!!! (Fix Filepatch)

### ISSUE THREAD

**Issue by griha41** [SchnitzelPommes/DayZ-SA-Tomato#26]
**Describe the bug**
Make file patch work again.

**Way to fix**
Since DayZ has version 1.0 you need to update startup parameters (of your server). So add in startup: "-filePatching". It will not create a 1-st level folders but other files and folders will work fine.

**Comment by SchnitzelPommes** [comment]
This Fixes File Write that true but MakeDir does still now work

**Comment by JakeDaBoss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [File System](https://trello.com/c/W4BcyVSb/4-file-system)
