### ISSUE TITLE
Teleport in-game bugged

### ISSUE THREAD

**Issue by JakeDaBoss** [SchnitzelPommes/DayZ-SA-Tomato#27]
**Describe the bug**

Teleport list is empty despite TeleportLocation.txt being populated.

Furthermore, it appears that the server crashes when "Add Current Location" is used.

**To Reproduce**
Open up mod.
Teleport tab.
Empty.

(Additional: Try to add current location.)

**Expected behavior**

**Screenshots**
https://cdn.discordapp.com/attachments/524215946466951168/524228372897988618/Untitled.png

**Comment by SchnitzelPommes** [comment]
Teleport list contains spaces?

**Comment by SchnitzelPommes** [comment]
If tp location is empty the file is nor found make sure it is DayZ-Sa-Tomato/Config/

**Comment by phatbank** [comment]
I've confirmed issue on my server too.
@DayZ-SA-Tomato\Config\List\TeleportLocation.txt
--doesn't show a list in teleport tab.

SchnitzelPommes stated DayZ-Sa-Tomato/Config/
--copy/paste teleportlocation.txt to that folder and still blank..
--i deleted the client side tomato mod and redownloaded via DayZsalauncher, now showing the teleportlocation file in both config/ and config/list but still blank. 

I have not poked around in the code yet, but as an end-user installation process, it doesnt work and crashes server.

**Comment by SchnitzelPommes** [comment]
did you copy to ur server DayZ-SA-Tomato\Config\List\TeleportLocation.txt
there is no way its blank
`protected string m_TeleportLocationsPath = "$CurrentDir:\\DayZ-Sa-Tomato\\Config\\List\\TeleportLocation.txt";`
```
void LoadTeleportLocations(PlayerIdentity admin)
	{
		m_TeleportLocations.Clear();
		FileHandle TpList = OpenFile(m_TeleportLocationsPath, FileMode.READ);
		if (TpList != 0)
		{
			string a =";";
			int i = 0;
			string line_content = "";
			while ( FGets(TpList,line_content) > 0 )
			{
			
				TStringArray strs = new TStringArray;
				m_TeleportLocations.Insert(i,line_content);
				Print("Adding Number : " + i + " line : " + line_content + " To the Teleport List!");
				i++;
			}
			CloseFile(TpList);
			SendTeleportList(admin);
		}
		Print("TpList = NULL");
	}
`
```

**Comment by SchnitzelPommes** [comment]
check your script.log

**Comment by cdiehr** [comment]
`protected string m_TeleportLocationsPath = "$CurrentDir:\\DayZ-Sa-Tomato\\Config\\List\\TeleportLocation.txt";`

Doesn't it have to be

`protected string m_TeleportLocationsPath = "$CurrentDir:\\@DayZ-Sa-Tomato\\Config\\List\\TeleportLocation.txt";`

**Comment by SchnitzelPommes** [comment]
Installation Instructions 

> Copy DayZ-SA-Tomato to your Server/Client main Folder

I dont see any @ here

**Comment by SchnitzelPommes** [comment]
also 

> If You need to use the mod folder with an @ Make sure to create DayZ-Sa-Tomato Folder with the Config Folder in it or it wont load Admins.txt and TpLocations file

**Comment by cdiehr** [comment]
ok, I try it.

**Comment by phatbank** [comment]
I got it working with removing @ from folder, but i looked at the code for Filehandler.c and noticed:

string TeleportFile = CustomizationFolderPath + "Teleport_Locations.txt";

--An underscore ( _ ) in .txt name, i placed teleportlocations.txt with and without the _ in the folder and its working.

Anyway, Excellent job with this tool! My  admins and I are very excited to have it.

**Comment by SchnitzelPommes** [comment]
that will be used in the next update new filesystem

good if it works now
