### ISSUE TITLE
Players getting kicked because of modded files.

### ISSUE THREAD

**Issue by krcenov** [SchnitzelPommes/DayZ-SA-Tomato#3]
**Describe the bug**
The server crashes on startup without a reason.

**To Reproduce**

verifySignatures = 1;  

1. Start server with mod
2. Let a player join server
3. Player kicked

**Expected behavior**
Not to kick players.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Latest

https://i.imgur.com/cS6nipk.png

https://i.imgur.com/RRKAHpp.png

https://i.imgur.com/5yTfbxJ.png

**Comment by SchnitzelPommes** [comment]
Yes it's an Client mod so your players would need it too or set checksignature to 0
Players can not access the menu since they are not in the admin.txt

**Comment by krcenov** [comment]
@SchnitzelPommes Players have it, yet they get kicked.

**Comment by SchnitzelPommes** [comment]
And you don't?

**Comment by krcenov** [comment]
Thr server has it too..

**Comment by SchnitzelPommes** [comment]
Check Installation Steps all player need to have the mod installed
