### ISSUE TITLE
keep getting error admin menue is client 

### ISSUE THREAD

**Issue by lonewolfss** [SchnitzelPommes/DayZ-SA-Tomato#31]
keep getting error admin menue is client  what dose this mean ???

**Comment by RagefaceMcW** [comment]
The message "admin menu is client" is not an error but a message saying that client side is correctly configured. If no menu appears you have to check server side configuration.

**Comment by SchnitzelPommes** [comment]
i suggest you visit our discord channel an read the faq section

**Comment by MichaelReibel** [comment]
Same here, I've installed the mod 5 Times over and over, still "admin menu is client"

script.log says "Dayz-Sa-Tomato initialized ..
Addin Admin: myid To the Admin List!
But when I Press M "Admin Menu Is Client".

**Comment by RagefaceMcW** [comment]
https://discord.gg/SsEnUU5

**Comment by dayzciv** [comment]
Likely, the issue is relatively simple: either your Admins.txt file is NOT a .txt or has a GUID instead of ID64, or  serverside, you might not have the toggle case-sensitive as necessary with DayZ Server.

**Comment by MichaelReibel** [comment]
It tourned out Step 2 of the Installation-Instructions (https://github.com/Tomato-dayZ/DayZ-SA-Tomato#installing) is wrong/incomplete "Copy SchnitzelPommes.bikey to your Servers keys folder".
**The Key needs to be copied not only to the Servers Keys-Folder but to the Clients Keys-Folder as well.**

**Comment by SchnitzelPommes** [comment]
no it does not need to be there

**Comment by GooseWithAKnife** [comment]
> 
> 
> It tourned out Step 2 of the Installation-Instructions (https://github.com/Tomato-dayZ/DayZ-SA-Tomato#installing) is wrong/incomplete "Copy SchnitzelPommes.bikey to your Servers keys folder".
> **The Key needs to be copied not only to the Servers Keys-Folder but to the Clients Keys-Folder as well.**

There is no **Client** key folder. The only keys folder is the server as it's the one doing the authentication.
