### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Nekonika** [SchnitzelPommes/DayZ-SA-Tomato#37]
Since the last Update I am getting this warning message:
"Can't compile "Mission" script module!"

![image](https://user-images.githubusercontent.com/51423438/60389433-1d276f00-9ac1-11e9-9e02-b31d90e17c8b.png)

I'm not quite sure if this is a bug or if it's related to the new update,
I've tried reinstalling the entire DayZ-Server and setting it up with a fresh download of your mod but even this doesn't seem to work.
If you need any more information, feel free to just ask for it.

**Comment by feiercrack** [comment]
same here, with v1.04.151979 in legit steam version.

error comes 1st from server, then same error from client.

with v1.03.151658 in crc version no problems

**Comment by tm931124** [comment]
same here

**Comment by Markelens** [comment]
Mod is no longer in development.
