### ISSUE TITLE
cant open admin panel if somebody logs in first

### ISSUE THREAD

**Issue by wallker0** [SchnitzelPommes/DayZ-SA-Tomato#4]
**Describe the bug**
I cant open the admin menu if other player log in before me on my server

**To Reproduce**
1. let somebody whos not on the admin list log in first
2. log in
3. try to open the menu

**Expected behavior**
the menu should open

** Also cant open the menu if I relog

**Desktop (please complete the following information):**
 - OS: win10

**Comment by SchnitzelPommes** [comment]
Oh that is the bug iwas looking for last days had this some times but didnt know where it was comming from looking into it today 
Thank you

**Comment by SchnitzelPommes** [comment]
Iam gonna make custom logging next so we can investigate why this is happening

**Comment by SchnitzelPommes** [comment]
Fixed
