### ISSUE TITLE
Can we see the full map?

### ISSUE THREAD

**Issue by krcenov** [SchnitzelPommes/DayZ-SA-Tomato#9]
**Is your feature request related to a problem? Please describe.**
I can not see the full map on max zoom out.
The map starts zoomed in at max.

**Describe the solution you'd like**
Please make it so the full map can be seen when zoomed out at maximum.
Please make it so the map starts centered and zoomed out untill it can be seen fully.

![screenshot_1](https://user-images.githubusercontent.com/23533561/49173840-71147e80-f34d-11e8-88cd-e278e2abe445.png)

**Comment by SchnitzelPommes** [comment]
there are no setting for the map widget i cannot change anything there sorry
